---
  - name: create global nginx conf dir
    file: dest=/etc/nginx/conf/global state=directory
    sudo: yes

  - name: copy nginx global conf
    copy: src={{ item }}.conf dest=/etc/nginx/conf/global/{{ item }}.conf
    with_items:
      - restrictions
      - cors
    sudo: yes
    notify: restart nginx

  - name: copy server confs
    template: src=iipsrv.j2 dest=/etc/nginx/nginx.conf
    sudo: yes
    notify: restart nginx

  - name: make sure iipsrv dir exists
    file: path=/usr/share/nginx/iipsrv state=directory
    sudo: yes

  - name: make sure manifests dir exists
    file: path=/usr/share/nginx/iipsrv/manifests state=directory
    sudo: yes

  - name: make sure images dir exists
    file: path=/usr/share/nginx/iipsrv/images state=directory
    sudo: yes

  - name: copy index.html
    template: src=index.j2 dest=/usr/share/nginx/iipsrv/index.html
    sudo: yes
